### ISSUE TITLE
nomintim-updatedb/nominatim-apache: PHP module dotenv not installed

### ISSUE THREAD

**Issue by ghost** [chesty/nominatim-docker#4]
Nomintim logs show

2021-02-20 09:10:13+UTC -- /usr/local/bin/nominatim-docker-entrypoint.sh: starting nominatim-updatedb
2021-02-20 09:10:13+UTC -- /usr/local/bin/nominatim-docker-entrypoint.sh: nominatim-updatedb called
PHP Warning:  require(Symfony/Component/Dotenv/autoload.php): failed to open stream: No such file or directory in /Nominatim/lib-php/dotenv_loader.php on line 3
PHP Fatal error:  require(): Failed opening required 'Symfony/Component/Dotenv/autoload.php' (include_path='.:/usr/share/php') in /Nominatim/lib-php/dotenv_loader.php on line 3

Containers stay in state "Restarting".

**Comment by chesty** [comment]
cheers. should be fixed in an hour to two.

**Comment by chesty** [comment]
looks good to go. vroom updating now if you're using that.
